[build]
command = "yarn build"       # Build command
publish = "dist"             # Folder for the build result (default for Vite is dist)
functions = "netlify/functions"

[[redirects]]
from = "/*"                 # Any request that doesn't match a static file
to = "/index.html"          # Redirect to index.html, so React Router can handle the routing
status = 200

[build.environment]
NODE_VERSION = "20.19.0"